spring:
  application:
    name: spring boot graphql api server demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:graphql;MODE=MySQL;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:schema/mysql-init.sql'
    username: sa
    password: sa
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      pool-name: "[H2] DataSourcePool"
  jpa:
    database: mysql
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
server:
  port: 8080
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true